### ISSUE TITLE
skin.min.css has a bug

### ISSUE THREAD

**Issue by dgt41** [tinymce/tinymce#3095]
The default skin has these:
```css
.mce-ico{font-family:'tinymce',Arial;font-style:normal;font-weight:normal;font-variant:normal;font-size:16px;line-height:16px;speak:none;vertical-align:text-top;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;display:inline-block;background:transparent center center;background-size:cover;width:16px;height:16px;color:#333}

.mce-btn-small .mce-ico{font-family:'tinymce-small',Arial}
```
The second pair of classes should not contain a space between them `.mce-btn-small .mce-ico` otherwise the font will always be `tinymce-small` and thus missing a lot of icons
