### ISSUE TITLE
Full Screen in Inline Mode

### ISSUE THREAD

**Issue by donShakespeare** [tinymce/tinymce#3692]
Related to old issue https://github.com/tinymce/tinymce/issues/2474
@CaptinJackSparow it does not work in inline mode because it is not designed to.
If you open up the Fullscreen plugin JS file you will notice this
```javascript
if (editor.settings.inline) {
  return; // this means inline is, unfortunately, no show!!
}
```
https://github.com/tinymce/tinymce/blob/136c0341aa9f43b720d5942498ed1796f1cb2ccf/src/plugins/fullscreen/src/main/js/Plugin.js#L30

@spocke 
>Not sure what you want the editor to do when you switch to fullscreen in an inline environment

I think the OP wants exactly what happens in the iframe environment, namely *distraction-free* mode.
Basically to add/remove a CSS class (which the OP can style accordingly) on the inline RTE DIV when
`editor.addCommand('mceFullscreen')` is fired/toggled. Or perhaps the default classname `.mce-fullscreen` might even work

Maybe the official plugin can incorporate inline mode???

I acheive this by intercepting the fullscreen plugin only when my users are in inline mode
```javascript
if(userWantsFullscreenInline){
  tinymce.PluginManager.add('fullscreen', function(editor) {
    editor.addCommand('mceFullscreen', function() {
      if($(editor.getBody()).hasClass('tw-fullscreen-inline')){
        $(editor.getBody()).removeClass('tw-fullscreen-inline');
      }
      else{
        $(editor.getBody()).addClass('tw-fullscreen-inline');
      }
      editor.focus();
    });
    editor.addButton('fullscreen', {
     icon: 'fullscreen',
     cmd: 'mceFullscreen',
     title: 'Fullscreen'
    });
    editor.addMenuItem('fullscreen', {
     icon: 'fullscreen',
     cmd: 'mceFullscreen',
     text: ' Fullscreen'
    });
  });
```

and the fullscreen CSS is rather generic
```css
.tw-fullscreen-inline {
    position: fixed!important;
    top: 0!important;
    left: 0!important;
    width: 100%!important;
    height: 90%!important;
    max-height: 90%!important;
    z-index: 99!important;
    padding: 2%!important;
    overflow: auto!important;
}
```
