### ISSUE TITLE
(5.x) Collection grid has max-height that doesn't auto-adjust

### ISSUE THREAD

**Issue by Paril** [tinymce/tinymce#4762]
Charmap is a good example of this issue. Adding new tabs doesn't let the content expand.
![](https://i.imgur.com/UmjLeob.png)

**Comment by Evertvdw** [comment]
Using this custom (scss in this case) fixes the issue:
```scss
.tox-form {
	height: 100% !important;

	&__group--collection {
		height: calc(100% - 54px) !important;
	}

	.tox-collection__group {
		max-height: auto !important;
	}
}

```
