### ISSUE TITLE
Grunt build of 5 RC2 generates different skin styles than Tiny-hosted version

### ISSUE THREAD

**Issue by martyf** [tinymce/tinymce#4781]
When testing out the plugin work from last week using RC2, I did a build using Grunt of the latest 5.x build from Github.

I've noticed two issues:
1. Toolbar buttons that have a label have an unnecessary width applied (removing the "text" from the addButton call shows a correct square button)
2. Base TinyMCE style has a 10px border radius added

![tiny-grunt](https://user-images.githubusercontent.com/1491079/51570763-1b46f780-1ef4-11e9-9668-c219b143a073.png)
![tiny-rc2](https://user-images.githubusercontent.com/1491079/51570755-184c0700-1ef4-11e9-9b20-8844ea44ef5d.png)

This created the following style declaration:
```css
.tox .tox-tbtn__select-label {
    cursor: default;
    font-weight: normal;
    margin: 0 4px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    width: 7em;
}
```
This creates unnecessary space on a toolbar button which has a string label - the difference is from "overflow: hidden;" to the end.

It is like the UI is treating a button as a button with dropdown behaviour (Split button) - but actually doesn't add any additional markup to that effect. Those other styles to me show it would have a set width, overflowed text hidden and 'continued' with the ellipsis, which I would expect with a button with dropdown.

The Tiny-hosted version style differs:
```css
.tox .tox-tbtn__select-label {
  cursor: default;
  font-weight: normal;
  margin: 0 4px;
}
```

Additionally, the grunt build version has a border-radius on the base .tox-tinymce class:

```css
.tox-tinymce {
  border: 1px solid #cccccc;
  border-radius: 10px;
  box-shadow: none;
  box-sizing: border-box;
  display: flex;
  flex-direction: column;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
  overflow: hidden;
  visibility: inherit !important;
}
```

Compared to the Tiny-hosted version:
```css
.tox-tinymce {
  border: 0;
  box-sizing: border-box;
  display: flex;
  flex-direction: column;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
  overflow: hidden;
  padding: 0;
  visibility: inherit !important;
}
```

In a demo of the plugin using the hosted version does not exhibit these issues.

Tracing back through the node_modules from the grunt build version, you can see the style declarations in:
`ephox/oxide/build/skins/ui/skin.css`
