### ISSUE TITLE
TinyMCE 5: Inconsistent border color on .tox-color-input element

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4919]
```css
.tox .tox-textfield {
    border-color: #ccc;
}
.tox .tox-color-input span {
    border-color: rgba(34,47,62,.2);
}
```
Both should use the same color.
