### ISSUE TITLE
TinyMCE Editor does not appear, if the <textarea> is inside a popup modal

### ISSUE THREAD

**Issue by deyuaru** [tinymce/tinymce#7347]
If the <textarea> is on the page, it works as intended.

If the <textarea> is inside a popup, instead of TinyMCE editor appearing, it is just a normal textarea textbox.

Is there a reason to why it cannot be used inside a modal, or is it because the modal is not part of the page (using @components in Laravel)

**Comment by lorenzo-pomili** [comment]
Hello @deyuaru,

I was not able to reproduce the issue, could you provide a [fiddle](https://fiddle.tiny.cloud/) or a repo that reproduces it?

Thanks

**Comment by deyuaru** [comment]
sry, we have opted for a different textbox UI, as per requirement change.

Thank you for your time.

**Comment by kkYFL** [comment]
use tinymce in Modal,open the firstTime work well,open the second time,doesn't work,can not click ,can not input

**Comment by Evashasha** [comment]
I've met the same problem. I resolved it by changing the position of the menu as below👇
```css
body.tox-fullscreen .tox.tox-tinymce.tox-fullscreen {
    z-index: 1000001;
}

.tox.tox-silver-sink.tox-tinymce-aux {
    z-index: 1000001;
}
```
I'm looking forward a better resolution. 🌹💗☀️🥺
