### ISSUE TITLE
*styles* toolbar item crashes in some specific circumstances

### ISSUE THREAD

**Issue by Sheraff** [tinymce/tinymce#9840]
In some specific cases when opening the `styles` toolbar which evaluates a lot of styles, we get a console error and the panel doesn't open. The editor keeps working, but the styles panel cannot be used.

*I cannot provide a reproduction because I haven't managed to reproduce consistently outside of the actual location in our app...*

**A quick diagnosis**

When evaluating the `color` property from `previewStyles` of a *bold* (`<strong>`) element, we observe the `value` from `let value = getComputedStyle(name, previewElm);` being `undefined`.

This results in the following error

```shell
theme.js:12890 

Uncaught
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at Array.<anonymous> (tinymce.js:20756:36)
    at Qa (tinymce.js:541:18)
    at rz (tinymce.js:20747:7)
    at Object.getCssText (tinymce.js:178:19)
    at Object.getStylePreview (theme.js:19891:58)
    at o (theme.js:23231:24)
    at n (theme.js:23240:18)
    at theme.js:23212:63
    at nt (theme.js:225:16)
    at mo (theme.js:309:39)
```

Which we can trace back to https://github.com/tinymce/tinymce/blob/4870f4c5faaa71c37a6c9c50dcdcfa1d623b7bc9/modules/tinymce/src/core/main/ts/fmt/Preview.ts#L295-L301

We are using
- `"@tinymce/tinymce-react": "^5.1.0"` on `"react": "18.3.1",`
- which pulls in `tinymce: 6.8.3` as a dependency

Going in a little more details: it seems to be that the `DOMUtils` method `getStyle` returns `undefined` because in https://github.com/tinymce/tinymce/blob/4870f4c5faaa71c37a6c9c50dcdcfa1d623b7bc9/modules/tinymce/src/core/main/ts/api/dom/DOMUtils.ts#L463-L468

`SugarNode.isHTMLElement(SugarElement.fromDom(node))` inside `isHTMLElement` returns to `false` for the `<strong>` element (even though all went fine for the previous elements `h1`, `h2`, `h3`, ...)

---

Do you think it would be possible to make a patch release of `tinymce` (and then of `@tinymce/tinymce-react` including it) to add a handling of the case where `value` is `undefined`?

**Comment by nedprofit** [comment]
We have a similar case. I can't reproduce exactly what led to this.

**Comment by joshsmith-cs** [comment]
Same issue for us — in `Chrome` and `Safari`. Works in `Firefox`.

**Comment by tvdeyen** [comment]
Looks like a duplicate of https://github.com/tinymce/tinymce/issues/9739

**Comment by tvdeyen** [comment]
We are using just the tinymce npm package (no react) and verified the bug in 7.1.1, 7.2.0, 7.2.1 and 7.3.0

FYI @spocke

**Comment by nedprofit** [comment]
We use Bun for minification. The partial shutdown of standard minification helped us.

```
const config = {
  sourcemap: 'external',
  entrypoints: ['app/javascript/application.js'],
  outdir: path.join(process.cwd(), 'app/assets/builds'),
  minify: {
    whitespace: true,
    identifiers: false,
    syntax: true,
  },
...
```

**Comment by tvdeyen** [comment]
```yaml
- title: Wrappers
  items:
    - title: Centered section
      block: div
      classes: [centered]
      wrapper: true
    - title: Indented section
      block: div
      classes: [indented]
      wrapper: true
    - title: Deep Indented section
      block: div
      classes: [deep-indented]
      wrapper: true
    - title: Small section
      block: div
      classes: [small]
      wrapper: true
```
